"""Derives the item tables in `../backlog.md` and `../backlog-done.md` from the items themselves.

`../method/IDM-011-the-backlog.md` is canonical for the scheme; this is the instrument.

**Nothing here detects where an item begins.** That was a judgement call made once, by a person, and
recorded in the file as a metadata line. An item *is* something carrying one. So a boundary this
script gets wrong is a boundary somebody wrote wrong, which is visible in the diff — rather than a
parser's opinion, which is not.

**The description column is not authored twice either.** It is the item's own opening sentence, or
its `###` heading. A second copy of a one-line summary is a second thing to go stale, and this
repository has four recorded instances of exactly that.

Usage, from anywhere:

    python3 docs/procedures/backlog-index.py            # print both tables
    python3 docs/procedures/backlog-index.py --write    # splice them into the two files
    python3 docs/procedures/backlog-index.py --check    # exit 1 if either file is stale or invalid

An optional second argument names a different repository root, so the script can be exercised
against a scratch copy without touching the real files.

## Three item shapes, because the file has three

| Shape | How the id is carried |
|---|---|
| prose opening with a bold sentence | a metadata line directly under it |
| a `###` subsection | a metadata line directly under the heading |
| a row of a table, where a whole section is one table | an extra leading cell holding the id |

## What it will not let you get away with

Ids out of file order, duplicated, or malformed. A status outside the five. A `done` item still in
`backlog.md`, or a non-`done` item in `backlog-done.md`. A `done` item with no completion date or
phase. **And a metadata line whose category disagrees with the section it sits in** — the category
is deliberately written in two places, and this is what makes that safe.

A citation `BKL-NNNN` anywhere under `docs/` naming an id no item carries is reported too. *Note
what that can and cannot catch: ids are never reused and never renumbered, and no status removes an
item from the scheme — `done` moves it to the other file and the rest stay put. So a citation cannot
break by drift. It can only be a typo, which is still worth catching and is all this check claims.*
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

BEGIN = "<!-- generated by procedures/backlog-index.py — do not edit between these markers -->"
END = "<!-- end generated -->"

STATUSES = ("open", "partly-done", "done", "refused", "superseded")

# `**BKL-0007** · category · status · added 2026-08-19` and, for a done item,
# `· done 2026-09-04 · phase 13`.
META = re.compile(
    r"^\*\*(?P<id>BKL-\d{4})\*\*\s+·\s+(?P<cat>[^·]+?)\s+·\s+(?P<status>[^·]+?)"
    r"(?:\s+·\s+added\s+(?P<added>\d{4}-\d{2}-\d{2}))?"
    r"(?:\s+·\s+done\s+(?P<done>\d{4}-\d{2}-\d{2}))?"
    r"(?:\s+·\s+phase\s+(?P<phase>\d+))?\s*$"
)
# A table-row item carries its id in the first cell.
ROW = re.compile(r"^\|\s*`(?P<id>BKL-\d{4})`\s*\|(?P<rest>.*)$")
CITATION = re.compile(r"\bBKL-\d{4}\b")


@dataclass
class Item:
    id: str
    category: str
    status: str
    added: str | None
    done: str | None
    phase: str | None
    what: str
    section: str
    line: int


# The eight category tokens, one per section of `../backlog.md`, written out rather than derived.
#
# Derivation was tried and produced `documentation-defects-found-and-not-fixed` — a token nobody
# would type into a citation. An explicit mapping is also the project's stated preference over a
# clever generic one, and it has a second use: a heading this table does not know is **refused**,
# so renaming a section cannot silently invent a ninth category.
CATEGORIES = {
    "Method — how work is planned, reviewed and recorded": "method",
    "Documentation defects found and not fixed": "documentation-defects",
    "Decisions waiting on a person": "decisions-waiting",
    "Measurements left open": "measurements",
    "Work with an owner-shaped decision behind it": "owner-shaped",
    "Instruments and housekeeping": "instruments",
    "Dictionaries": "dictionaries",
    "Not on this list, and why": "not-on-this-list",
}


def opening_sentence(lines: list[str], meta_at: int) -> str:
    """The item's own first sentence: the bold run above its metadata line, or a `###` heading.

    Wrapped lines are joined. Nothing is authored here — whatever the item says about itself is
    what the table says about it.
    """
    i = meta_at - 1
    while i >= 0 and not lines[i].strip():
        i -= 1
    if i < 0:
        return ""
    if lines[i].startswith("### "):
        return lines[i][4:].strip()
    # Walk back to the start of the paragraph, then take its leading bold run.
    start = i
    while start > 0 and lines[start - 1].strip():
        start -= 1
    para = " ".join(x.strip() for x in lines[start : i + 1])
    m = re.match(r"\*\*(.+?)\*\*", para)
    return (m.group(1) if m else para).strip()


def parse(path: Path) -> tuple[list[Item], list[str]]:
    """Every item in one file, in file order, plus whatever is wrong with them."""
    if not path.exists():
        return [], [f"MISSING: {path.name} does not exist"]
    lines = path.read_text().split("\n")
    items: list[Item] = []
    problems: list[str] = []
    section = ""
    generated = False
    for n, line in enumerate(lines):
        # Skip the block this script writes. A generated row and a table-row *item* are the same
        # shape — `| \`BKL-0009\` | … |` — so without this the second run parses its own output
        # back in and reports every id as a duplicate of itself. Found by running --write then
        # --check, which is the only order in which it happens.
        if line.startswith(BEGIN):
            generated = True
            continue
        if line.startswith(END):
            generated = False
            continue
        if generated:
            continue
        if line.startswith("## "):
            section = line[3:].strip()
            continue
        m = META.match(line)
        if m:
            items.append(
                Item(
                    id=m.group("id"),
                    category=m.group("cat").strip(),
                    status=m.group("status").strip(),
                    added=m.group("added"),
                    done=m.group("done"),
                    phase=m.group("phase"),
                    what=opening_sentence(lines, n),
                    section=section,
                    line=n + 1,
                )
            )
            continue
        r = ROW.match(line)
        if r:
            cells = [c.strip() for c in r.group("rest").split("|")]
            # id · category · status · added · what — the leading-cell shape IDM-011 specifies.
            if len(cells) < 5:
                bad = r.group("id")
                problems.append(f"{path.name}:{n + 1}  ROW ITEM WITH TOO FEW CELLS: {bad}")
                continue
            items.append(
                Item(
                    id=r.group("id"),
                    category=cells[0],
                    status=cells[1],
                    added=cells[2] if cells[2] not in ("", "—") else None,
                    done=None,
                    phase=None,
                    what=cells[4] if len(cells) > 4 else cells[3],
                    section=section,
                    line=n + 1,
                )
            )
    return items, problems


def validate(live: list[Item], done: list[Item]) -> list[str]:
    """Everything the scheme promises, checked. One line per broken promise."""
    problems: list[str] = []
    every = live + done

    seen: dict[str, Item] = {}
    for it in every:
        if it.id in seen:
            problems.append(f"DUPLICATE ID: {it.id} at line {it.line} and line {seen[it.id].line}")
        seen[it.id] = it
        if it.status not in STATUSES:
            problems.append(f"{it.id}: STATUS {it.status!r} is not one of {', '.join(STATUSES)}")
        expected = CATEGORIES.get(it.section)
        if expected is None:
            problems.append(f"{it.id}: UNKNOWN SECTION {it.section!r} — add it to CATEGORIES")
        elif it.category != expected:
            problems.append(
                f"{it.id}: CATEGORY {it.category!r} disagrees with its section ({expected!r})"
            )

    # File order, per IDM-011: ids ascend top to bottom **within each file**, not across the two.
    #
    # Not across: a done item moves to `backlog-done.md` and leaves a gap behind it, so the two
    # files interleave by construction. Checking the concatenation reported `BKL-0004` — the first
    # item ever moved — as following `BKL-0036`. Found by running it, not by reading it.
    for group in (live, done):
        for a, b in zip(group, group[1:]):
            if a.id >= b.id:
                problems.append(f"OUT OF FILE ORDER: {b.id} follows {a.id}")

    # Only `done` leaves backlog.md, and only `done` may be in backlog-done.md.
    for it in live:
        if it.status == "done":
            problems.append(f"{it.id}: status is done but it is still in backlog.md")
    for it in done:
        if it.status != "done":
            problems.append(f"{it.id}: is in backlog-done.md with status {it.status!r}")
        if not it.done or not it.phase:
            problems.append(f"{it.id}: done items need a completion date and a phase")

    return problems


def citations(root: Path, known: set[str]) -> list[str]:
    """Any `BKL-NNNN` written under docs/ or in CLAUDE.md that no item carries."""
    problems: list[str] = []
    targets = sorted((root / "docs").rglob("*.md"))
    claude = root / "CLAUDE.md"
    if claude.exists():
        targets.append(claude)
    for f in targets:
        for n, line in enumerate(f.read_text().split("\n"), 1):
            for cited in CITATION.findall(line):
                if cited not in known:
                    problems.append(f"{f.relative_to(root)}:{n}  CITES UNKNOWN {cited}")
    return problems


def table(items: list[Item], *, with_completion: bool) -> str:
    head = "| ID | Added | Status | Category | What it is | Done | Phase | See |"
    rule = "|---|---|---|---|---|---|---|---|"
    out = [head, rule]
    for it in items:
        done = it.done or "" if with_completion else ""
        phase = it.phase or "" if with_completion else ""
        out.append(
            f"| `{it.id}` | {it.added or '—'} | {it.status} | {it.category} | {it.what} "
            f"| {done or '—'} | {phase or '—'} | |"
        )
    return "\n".join(out)


def splice(target: Path, rendered: str, mode: str) -> int:
    text = target.read_text()
    if BEGIN not in text or END not in text:
        print(f"NO MARKERS: {target.name} has no generated block — add the two comment markers")
        return 1
    head, _, rest = text.partition(BEGIN)
    _, _, tail = rest.partition(END)
    fresh = f"{head}{BEGIN}\n\n{rendered}\n\n{END}{tail}"
    if mode == "--write":
        target.write_text(fresh)
        print(f"wrote {rendered.count(chr(10)) - 1} rows into {target.name}")
    elif fresh != text:
        print(f"STALE: {target.name} does not match its items. Re-run with --write.")
        return 1
    else:
        print(f"{target.name} is current.")
    return 0


def main() -> int:
    mode = sys.argv[1] if len(sys.argv) > 1 else "--print"
    if mode not in ("--print", "--write", "--check"):
        print(__doc__)
        return 2

    root = Path(sys.argv[2]).resolve() if len(sys.argv) > 2 else Path(__file__).resolve().parents[2]
    live_path = root / "docs" / "backlog.md"
    done_path = root / "docs" / "backlog-done.md"

    live, p1 = parse(live_path)
    done, p2 = parse(done_path)
    problems = p1 + p2 + validate(live, done)
    problems += citations(root, {it.id for it in live + done})

    if problems:
        # Refuse to render at all: a half-written table spliced into the file is worse than none.
        for p in problems:
            print(p)
        return 1

    live_table = table(live, with_completion=False)
    done_table = table(done, with_completion=True)

    if mode == "--print":
        print(live_table)
        print()
        print(done_table)
        return 0

    rc = splice(live_path, live_table, mode)
    rc |= splice(done_path, done_table, mode)
    if mode == "--check" and rc == 0:
        print(f"{len(live)} live, {len(done)} done, {len(live) + len(done)} ids.")
    return rc


if __name__ == "__main__":
    sys.exit(main())
